### ISSUE TITLE
Integrate with react-hot-loader

### ISSUE THREAD

**Issue by joehua87** [ericclemmons/webpack-hot-server-example#4]
@ericclemmons Thank you for your helpful repo.
I've try to integrate with react-hot-loader without luck :( - (the commits is here https://github.com/joehua87/webpack-hot-server-example/commit/18213d322d1cec2ade7851a136cc908451923c52)
I think problem is that I cannot use **webpack-dev-middleware** in the the process start with webpack cli, would anyone have a workaround solution?

When I remove these line, it works but **not** reload client code

``` js
.use(webpackDevMiddleware(compiler, {
  noInfo: true,
  publicPath: config.output.publicPath
}))
.use(webpackHotMiddleware(compiler))
```

When I use `node src/server.js` instead of `webpack --watch`, it works but **not** reload server code

**Comment by ericclemmons** [comment]
I'm using `react-hot-loader` with my projects. What is the the problem you're having?  Things just aren't reloading on the client or...?

(Admittedly, having client-side HMR and React in _this_ project is entirely out of scope. This project shows that it's possible to avoid using `nodemon` with costly server restarts if you use `webpack` instead).

**Comment by joehua87** [comment]
Yes, I've got the idea.
I think we can make it reload on server, also client. But cannot make webpack-dev-middleware (use webpack.config.client.js) run in process start with webpack --watch (use webpack.config.js), maybe we can't do this with webpack. :grimacing:

**Comment by ericclemmons** [comment]
That's odd.  This project was taken from an existing, functioning work project that's been doing this for ~6 months now :D

``` js
import { Router as router } from "express";

import client from "../../webpack.config.client.babel";
import dev from "webpack-dev-middleware";
import hot from "webpack-hot-middleware";
import webpack from "webpack";

const compiler = webpack(client);

export default router()
  .use(dev(compiler, {
    noInfo: true,
    publicPath: "/",
    quiet: false,
  }))
  .use(hot(compiler))
;
```

We have HMR working on both sides.  You can't run `webpack-dev-server`, but you _can_ use `webpack-dev-middleware` with HMR successfully.

I have some other projects that do HMR on the client, but haven't put in the server-side HMR yet.  Hopefully this may help:

> https://github.com/ericclemmons/npm-install-webpack-plugin/tree/master/example/webpack1

Sorry to close the issue, but it's not really something I can address here.  What I _can_ tell you is that HMR works on both the server & the client with React.  What I _don't_ know is if there's an issue with the latest `react-hot-loader` beta.  (I've heard there are some SSR issues!)
