### ISSUE TITLE
kube?

### ISSUE THREAD

**Issue by uptownhr** [ericclemmons/webpack-hot-server-example#5]
I saw you recently starred kube. I would love to hear your thought...

**Comment by ericclemmons** [comment]
Saw it on HN, thought it looked interesting!

> https://github.com/uptownhr/kube

Maybe we could discuss in that repo?  It seems that kube is really new, so I planned on giving it a whirl sometime soon to see how it could help users out.

**Comment by uptownhr** [comment]
would love that. feel free to start a thread there.  what is kn btw?

**Comment by ericclemmons** [comment]
Haha, sorry, HN!  (HackerNews)

I'll open up an issue on kube when I get to try it out this week.  See you there!
